### PR TITLE
fixing needinfo hyperlink and modifying openstack bugs query to remov…

### PR DESCRIPTION
**Pull request by hmaheswa**
…e qa_verified bugs

Signed-off-by: Hemanth Maheswarla <hmaheswa@hmaheswa.remote.csb>

### CODE REVIEW

**Comment by hmaheswa** [comment]
@SrinivasaBharath please review this PR

**Comment by MohitBis** [comment]
LGTM

**Review by SrinivasaBharath — CHANGES_REQUESTED** [review]
Instead of modifying the file every time create a  file with the variables and assign the variable with the URLs. Whenever the modification is required for these URLs than in only one place to modify.

Is it possible to do it now or required to raise a separate issue?

**Comment by hmaheswa** [comment]
> Instead of modifying the file every time create a file with the variables and assign the variable with the URLs. Whenever the modification is required for these URLs than in only one place to modify.
> 
> Is it possible to do it now or required to raise a separate issue?

Sure Bharath, Me and Mohit are planning to take up the optimization tasks in the coming sprints, we will raise a seperate PR for them.

**Review by SrinivasaBharath — APPROVED** [review]

**Pull request merged**
